# Generated by Django 4.1.7 on 2023-03-30 12:48

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.IntegerField(choices=[(0, 'Junior Seeker'), (1, 'Senior Seeker'), (3, 'Guest Seeker')], default=0)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=600)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('meet_point', models.CharField(max_length=100)),
                ('expected_weather', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Clear'), (2, 'Chilly'), (3, 'Rainy'), (4, 'Snowy'), (5, 'Stormy')], default=0)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='events.guide')),
            ],
            options={
                'ordering': ['event_date', 'start_time'],
            },
        ),
    ]
