# Generated by Django 3.2.18 on 2023-03-31 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['uploaded_on']},
        ),
    ]
