# Generated by Django 3.2.18 on 2023-04-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='question_details',
        ),
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(default='test title', max_length=100),
            preserve_default=False,
        ),
    ]
